# Generated by Django 3.2.16 on 2022-12-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='category',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
