# Generated by Django 3.2.16 on 2022-12-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Email', '0002_email_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('details', models.TextField(max_length=200)),
            ],
        ),
    ]
